### PR TITLE
Adding in the data layer.

### PR DESCRIPTION
**Pull request by jpp3911**
Will comment and provide example usage later.

### CODE REVIEW

**Comment by jpp3911** [comment]
Added in the response class stuff. Will worry about logging and headers later.

**Comment by tlanclos** [comment]
Can you remove the double underbar at the beginning of those three modules? That convention doesn't fit PEP8.

**Comment by tlanclos** [comment]
Also convert the lines with multiple imports into multiple lines of imports to fit PEP8

**Comment by tlanclos** [comment]
Lastly for sql_model.py where you create a new flask app instance, use the one that's already created in ticketapi.py. `from ticketapi import app` should do the trick.

**Comment by tlanclos** [comment]
Should I pull this over and fix the issues, or did you want to patch them?

**Comment by jpp3911** [comment]
I'm not going to get around to it tonight for sure, so if you want to patch those you can or I can in a day or two.

**Comment by jpp3911** [comment]
Ayy lmao

**Comment by tlanclos** [comment]
I'm finding a few issues, mainly with the flask app and circular imports (since you'll need the flask app instance for the database stuff). I'm working out all the python stuff to organize everything lol.

**Pull request merged**
